---
- hosts: all
  become: true
  tasks:
    - name: install packages
      yum:
        name: "{{item}}"
        state: present
      with_items:        
                - httpd
                - git
                - docker
                - telnet
